### ISSUE TITLE
Not Compatable with JetBrains IntelliJ 2024.3

### ISSUE THREAD

**Issue by JoseJacin** [cquilezg/pitest-helper#68]
Since upgrading the JetBrains IntelliJ 2024.3, this plug-in has been flagged as `Incompatible: requires IDE build 242.* or earlier`

"I would create the PR myself, but I have no idea how the plugins work. Sorry :-)

Thanks.

**Comment by cquilezg** [comment]
Hi @JoseJacin,

Thank you for letting me know. I'll update the plugin today or tomorrow, when I've some free time.

I'll let you know.

**Comment by JoseJacin** [comment]
Ohhh, thanks!!

**Comment by cquilezg** [comment]
Hi again @JoseJacin,

I have updated the plugin to make it compatible with IntelliJ 2024.3. I have released the new version.
Can you download it and try it?

Thank you!

**Comment by JoseJacin** [comment]
Hello.

I have tried it and everything is installed and working correctly.

Thank you very much for the promptness!
